apiVersion: apps/v1
kind: Deployment
metadata:
  name: mockice-deployment
  labels:
    app: mockice
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mockice
  template:
    metadata:
      labels:
        app: mockice
    spec:
      containers:
      - name: mockice
        image: hudymi/mockice:gopher
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: mockice-service
spec:
  selector:
    app: mockice
  type: NodePort
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 32150
